import createImages from './src/index.js';

// Art Direction
createImages([
  [
    'public/commercial_copy.jpg',
    // 'w=600;800;900;1000',
    'w=800;500;600',
    'a=9:16',
    // 'f=avif;webp;jpg',
    'f=avif;webp;jpg',
    'fallbackWidth=700',
    'fallbackFormat=jpg',
    'alt=Image of house and pool with custom lighting',
    'sizes=100vw',
    'c=electricalImage',
    'media=(max-width: 600px)',
    'enlarge=true',
    'clean=true',
    // 'debug=true',
  ],
  [
    'public/commercial.jpg',
    'w=601;800;600',
    'a=4:3',
    'f=avif;webp;jpg',
    'fallbackWidth=700',
    'fallbackFormat=jpg',
    'alt=Image of house and pool with custom lighting',
    'sizes=100vw',
    'c=electricalImage',
    'media=(max-width: 600px)',
    'enlarge=true',
    'clean=true',
    // 'debug=true',
  ],
  [
    'public/commercial.jpg',
    'w=600;700;800',
    'a=16:9',
    'f=avif;webp',
    'fallbackWidth=700',
    'fallbackFormat=jpg',
    'alt=Image of house and pool with custom lighting',
    'sizes=100vw',
    'c=electricalImage',
    'media=(min-width: 601px)',
    'sharpen=true',
    'enlarge=true',
    'clean=true',
  ],
]);
